# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip" # Use pip for Python requirements
    directory: "/"           # Location of requirements.txt or pip manifest
    schedule:
      interval: "weekly"     # Check for updates every week
