version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # Looks for requirements.txt in project root
    schedule:
      interval: "daily"   # You can set to "daily", "monthly", etc.
    open-pull-requests-limit: 5
    commit-message:
      prefix: "pip"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    assignees:
      - "Into-The-Grey"    # Or your GH username
    reviewers:
      - "Into-The-Grey"
    rebase-strategy: "auto"
    # Uncomment the lines below if you want to ignore PySide2 updates
    # ignore:
    #   - dependency-name: "pyside2"

  # (Optional: Enable this if you use GitHub Actions!)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "github-actions"
      - "dependencies"
      - "python"
    assignees:
      - "Into-The-Grey"
    reviewers:
      - "Into-The-Grey"
    rebase-strategy: "auto"