version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # Looks for requirements.txt in project root
    schedule:
      interval: "weekly"   # You can set to "daily", "monthly", etc.
    open-pull-requests-limit: 5
    commit-message:
      prefix: "pip"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    assignees:
      - "Into-The-Grey"    # Or your GH username
    reviewers:
      - "Into-The-Grey"
    rebase-strategy: "auto"
    ignore:
      - dependency-name: "pyside2"
        # If you want to only update PySide2 manually, uncomment above and remove this comment

  - package-ecosystem: "pip"
    directory: "/"   # Looks for dev-requirements.txt if you add it below
    schedule:
      interval: "weekly"
    # This tells dependabot to look for dev dependencies
    requirements-file: "dev-requirements.txt"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "pip"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    assignees:
      - "Into-The-Grey"
    reviewers:
      - "Into-The-Grey"
    rebase-strategy: "auto"

  # (Optional: Enable this if you use GitHub Actions!)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "github-actions"
      - "dependencies"
    assignees:
      - "Into-The-Grey"
