name: Build Windows EXE (Manual)

on:
  workflow_dispatch:

jobs:
  build-exe:
    runs-on: windows-latest

    env:
      # Required secrets for OAuth functionality
      BUNGIE_API_KEY: ${{ secrets.BUNGIE_API_KEY }}
      BUNGIE_CLIENT_ID: ${{ secrets.BUNGIE_CLIENT_ID }}
      BUNGIE_REDIRECT_URI: ${{ secrets.BUNGIE_REDIRECT_URI }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/dev-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Upgrade pip and wheel
        run: |
          python -m pip install --upgrade pip wheel setuptools

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
          pip install pyinstaller

      - name: Create logs directory
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path RaidAssist/logs

      - name: Check required secrets
        run: |
          $missing = @()
          if ([string]::IsNullOrEmpty($env:BUNGIE_API_KEY)) { $missing += "BUNGIE_API_KEY" }
          if ([string]::IsNullOrEmpty($env:BUNGIE_CLIENT_ID)) { $missing += "BUNGIE_CLIENT_ID" }
          if ([string]::IsNullOrEmpty($env:BUNGIE_REDIRECT_URI)) { $missing += "BUNGIE_REDIRECT_URI" }
          if ($missing.Count -gt 0) {
            Write-Error "Missing required secrets: $($missing -join ', '). Build requires valid OAuth configuration."
            exit 1
          }
          Write-Output "All required OAuth secrets are present."
        shell: pwsh

      - name: Verify secrets for build
        run: |
          Write-Output "Checking OAuth configuration (values hidden for security):"
          Write-Output "BUNGIE_API_KEY: $([string]::IsNullOrEmpty($env:BUNGIE_API_KEY) ? 'NOT SET' : 'SET')"
          Write-Output "BUNGIE_CLIENT_ID: $([string]::IsNullOrEmpty($env:BUNGIE_CLIENT_ID) ? 'NOT SET' : 'SET')"
          Write-Output "BUNGIE_REDIRECT_URI: $([string]::IsNullOrEmpty($env:BUNGIE_REDIRECT_URI) ? 'NOT SET' : 'SET')"
        shell: pwsh

      - name: Build with PyInstaller
        run: pyinstaller raidassist.spec

      - name: Upload built EXE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: RaidAssist-Windows
          path: dist/**

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Build-Logs
          path: logs/
